
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jwzdnbgldfjkvjshagvs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3emRuYmdsZGZqa3Zqc2hhZ3ZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyODM5NTMsImV4cCI6MjA1ODg1OTk1M30.PzdX2folW-wZLOD_Shc0547X9MLiL9_B_k__burrqkQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
